// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovimentosManuais.Infrastructure.Data;

#nullable disable

namespace MovimentosManuais.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527042649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.MovimentoManual", b =>
                {
                    b.Property<short>("Mes")
                        .HasPrecision(2)
                        .HasColumnType("smallint")
                        .HasColumnName("DAT_MES");

                    b.Property<short>("Ano")
                        .HasPrecision(4)
                        .HasColumnType("smallint")
                        .HasColumnName("DAT_ANO");

                    b.Property<int>("NumeroLancamento")
                        .HasPrecision(18)
                        .HasColumnType("int")
                        .HasColumnName("NUM_LANCAMENTO");

                    b.Property<string>("CodigoProduto")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("COD_PRODUTO");

                    b.Property<string>("CodigoCosif")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("COD_COSIF");

                    b.Property<string>("CodigoUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("COD_USUARIO");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DAT_MOVIMENTO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DES_DESCRICAO");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VAL_VALOR");

                    b.HasKey("Mes", "Ano", "NumeroLancamento", "CodigoProduto", "CodigoCosif");

                    b.HasIndex("CodigoProduto", "CodigoCosif");

                    b.ToTable("MOVIMENTO_MANUAL", (string)null);
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.Produto", b =>
                {
                    b.Property<string>("CodigoProduto")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("COD_PRODUTO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DES_PRODUTO");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("STA_STATUS");

                    b.HasKey("CodigoProduto");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.ProdutoCosif", b =>
                {
                    b.Property<string>("CodigoProduto")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("COD_PRODUTO");

                    b.Property<string>("CodigoCosif")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("COD_COSIF");

                    b.Property<string>("CodigoClassificacao")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("COD_CLASSIFICACAO");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("STA_STATUS");

                    b.HasKey("CodigoProduto", "CodigoCosif");

                    b.ToTable("PRODUTO_COSIF", (string)null);
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.MovimentoManual", b =>
                {
                    b.HasOne("MovimentosManuais.Domain.Entities.ProdutoCosif", "ProdutoCosif")
                        .WithMany("Movimentos")
                        .HasForeignKey("CodigoProduto", "CodigoCosif")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProdutoCosif");
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.ProdutoCosif", b =>
                {
                    b.HasOne("MovimentosManuais.Domain.Entities.Produto", "Produto")
                        .WithMany("Cosifs")
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Cosifs");
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.ProdutoCosif", b =>
                {
                    b.Navigation("Movimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
