

CREATE TABLE MovimentosManuaisDb.dbo.PRODUTO (
	COD_PRODUTO char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DES_PRODUTO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STA_STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO)
)
go;

CREATE TABLE MovimentosManuaisDb.dbo.PRODUTO_COSIF (
	COD_PRODUTO char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	COD_COSIF varchar(11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	COD_CLASSIFICACAO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STA_STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_PRODUTO_COSIF PRIMARY KEY (COD_PRODUTO,COD_COSIF)
);
go;

ALTER TABLE MovimentosManuaisDb.dbo.PRODUTO_COSIF ADD CONSTRAINT FK_PRODUTO_COSIF_PRODUTO_COD_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES MovimentosManuaisDb.dbo.PRODUTO(COD_PRODUTO);
go;

CREATE TABLE MovimentosManuaisDb.dbo.MOVIMENTO_MANUAL (
	DAT_MES smallint NOT NULL,
	DAT_ANO smallint NOT NULL,
	NUM_LANCAMENTO int NOT NULL,
	COD_PRODUTO char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	COD_COSIF varchar(11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	VAL_VALOR decimal(18,2) NOT NULL,
	DES_DESCRICAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DAT_MOVIMENTO datetime2 NOT NULL,
	COD_USUARIO varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_MOVIMENTO_MANUAL PRIMARY KEY (DAT_MES,DAT_ANO,NUM_LANCAMENTO,COD_PRODUTO,COD_COSIF)
);
go;

 CREATE NONCLUSTERED INDEX IX_MOVIMENTO_MANUAL_COD_PRODUTO_COD_COSIF ON MovimentosManuaisDb.dbo.MOVIMENTO_MANUAL (  COD_PRODUTO ASC  , COD_COSIF ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
go;

ALTER TABLE MovimentosManuaisDb.dbo.MOVIMENTO_MANUAL ADD CONSTRAINT FK_MOVIMENTO_MANUAL_PRODUTO_COSIF_COD_PRODUTO_COD_COSIF FOREIGN KEY (COD_PRODUTO,COD_COSIF) REFERENCES MovimentosManuaisDb.dbo.PRODUTO_COSIF(COD_PRODUTO,COD_COSIF);
go;

CREATE OR ALTER PROCEDURE sp_MovimentoManual_Listar
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        MM.DAT_MES               AS Mes,
        MM.DAT_ANO               AS Ano,
        MM.NUM_LANCAMENTO        AS NumeroLancamento,
        MM.COD_PRODUTO           AS CodigoProduto,
        P.DES_PRODUTO            AS DescricaoProduto,
        MM.COD_COSIF             AS CodigoCosif,
        PC.COD_CLASSIFICACAO     AS DescricaoCosif,
        MM.VAL_VALOR             AS Valor,
        MM.DES_DESCRICAO         AS Descricao,
        MM.DAT_MOVIMENTO         AS DataMovimento,
        MM.COD_USUARIO           AS CodigoUsuario
    FROM MOVIMENTO_MANUAL MM
    INNER JOIN PRODUTO P
        ON P.COD_PRODUTO = MM.COD_PRODUTO
    INNER JOIN PRODUTO_COSIF PC
        ON PC.COD_PRODUTO = MM.COD_PRODUTO
        AND PC.COD_COSIF = MM.COD_COSIF
    ORDER BY
        MM.DAT_MES,
        MM.DAT_ANO,
        MM.NUM_LANCAMENTO;
END
go;

INSERT INTO MovimentosManuaisDb.dbo.PRODUTO (COD_PRODUTO,DES_PRODUTO,STA_STATUS) VALUES
	 (N'0001',N'Conta Corrente',N'A'),
	 (N'0002',N'Conta Poupanca',N'A'),
	 (N'0003',N'Credito Pessoal',N'A'),
	 (N'0004',N'Financiamento',N'A'),
	 (N'0005',N'Seguro Residencial',N'I');

INSERT INTO MovimentosManuaisDb.dbo.PRODUTO_COSIF (COD_PRODUTO,COD_COSIF,COD_CLASSIFICACAO,STA_STATUS) VALUES
	 (N'0001',N'11111111111',N'CC0001',N'A'),
	 (N'0001',N'11111111112',N'CC0002',N'A'),
	 (N'0002',N'22222222221',N'CP0001',N'A'),
	 (N'0002',N'22222222222',N'CP0002',N'A'),
	 (N'0003',N'33333333331',N'CR0001',N'A'),
	 (N'0003',N'33333333332',N'CR0002',N'A'),
	 (N'0004',N'44444444441',N'FN0001',N'A'),
	 (N'0005',N'55555555551',N'SG0001',N'I');